### ISSUE TITLE
Check install steps

### ISSUE THREAD

**Issue by ghost** [ret2basic/CTF-Pwnbox-Setup-Script#1]
Hi,
I think the installation steps needs to updated just slightly, it looks like one of the files may have changed names? Sorry if this is obvious, I'm pretty new to Linux and want to check I didn't do something wrong (it seems to be working though).

I used:
wget https://raw.githubusercontent.com/ret2basic/powerupmykali/main/powerupmykali.sh
chmod +x powerupmykali.sh
./powerupmykali.sh

**Comment by ret2basic** [comment]
Thank you, I have fixed README.md accordingly.
