### ISSUE TITLE
installing executables with 'go get' in module mode is deprecated

### ISSUE THREAD

**Issue by ghost** [ret2basic/CTF-Pwnbox-Setup-Script#2]
I received a message near the end of the installation
"go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'."

Most of the install seemed to go fine without any errors and I can use things like docker and sublime text that weren't installed before.

**Comment by ret2basic** [comment]
Thank you for letting me know, I have fixed the script. Wow, this change would hurt tons of projects.
